### ISSUE TITLE
Multiple .nii masks 

### ISSUE THREAD

**Issue by Fyousefirizi** [Sikerdebaard/dcmrtstruct2nii#13]
Is there a way to combine all the .nii masks? The presented code produces multiple masks for a patient depending on the number of the segmented regions as RT-struct.

**Comment by Sikerdebaard** [comment]
Unfortunately not from the dcmrtstruct2nii package. However, this could be easily accomplished with a package like [NiBabel](https://nipy.org/nibabel/gettingstarted.html)
