### ISSUE TITLE
InvalidFileFormatException

### ISSUE THREAD

**Issue by wwq1204** [Sikerdebaard/dcmrtstruct2nii#21]
I want to know why I have the following error:
rtstruct.dcm is not an rt-struct dicom.
but it is a rt-struct dicom file.

**Comment by Sikerdebaard** [comment]
This exception is raised on this line: https://github.com/Sikerdebaard/dcmrtstruct2nii/blob/master/dcmrtstruct2nii/adapters/input/contours/rtstructinputadapter.py#L23

Looks like you either gave it a directory or an invalid dicom / dicom without a StructureSetROISequence.
