### ISSUE TITLE
Single NIFTI file with all structures

### ISSUE THREAD

**Issue by monjoybme** [Sikerdebaard/dcmrtstruct2nii#29]
I need to generate a single NIFTI file with all the structures. As of now, this code generates multiple NIFTI files for multiple structures.

**Comment by Sikerdebaard** [comment]
Unfortunately this is currently unsupported. The reason for this is that structures can overlap and there is currently no strategy implemented to resolve overlaps.

Perhaps fslutils has a tool to do what you want. For example you could merge the NIfTI file outputs from dcmrtstruct2nii with `fslmerge` or perhaps `fslroi`.

https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/Fslutils
