### ISSUE TITLE
Numpy compatibility

### ISSUE THREAD

**Issue by craigrusselltiu** [Sikerdebaard/dcmrtstruct2nii#3]
Currently, this only works with numpy==1.15.4. Would it be possible to make it compatible with the latest numpy version, i.e. numpy==1.18.1? It would be great if I could use this with other medical imaging libraries such as pyradiomics.

**Comment by Sikerdebaard** [comment]
Done. Just pip install --upgrade dcmrtstruct2nii and you should be good to go.
