### ISSUE TITLE
Rt struct ring is being transformed to filled circle

### ISSUE THREAD

**Issue by michelatieh** [Sikerdebaard/dcmrtstruct2nii#31]
Hello,
When I am trying to transform a structure that has the form of a ring, the niftii file I am getting is a circle filled inside. Is there any way to maintain the ring structure? 
Thank you in advance.

**Comment by Sikerdebaard** [comment]
Hi @michelatieh. Unfortunately this is currently not supported as stated in the [README.md](https://github.com/Sikerdebaard/dcmrtstruct2nii#rasterization).
