### ISSUE TITLE
Code to fix in cases of a hole existed in the mask

### ISSUE THREAD

**Issue by soanduong** [Sikerdebaard/dcmrtstruct2nii#32]
The existing version works perfectly in cases of there is no hole in the mask. However it is not correct if a hole existed (i.e. in a slice, there is more than one contours). I found a simply way to address the issue by modify line 48 in [dcmrtstruct2nii/adapters/convert)/rtstructcontour2mask.py](https://github.com/Sikerdebaard/dcmrtstruct2nii/blob/master/dcmrtstruct2nii/adapters/convert/rtstructcontour2mask.py) by three lines of code as follows:

```
ex_mask = np_mask[z, ...] > 0

np_mask[z, ex_mask & filled_poly] = mask_background

np_mask[z, ex_mask ^ filled_poly] = mask_foreground
```

**Comment by Sikerdebaard** [comment]
A somewhat similar approach has been implemented through PR #37. Please upgrade to v3 to enable the new approach that supports holes out-of-the-box. `pip install --upgrade dcmrtstruct2nii==3`.
