### ISSUE TITLE
Recent update in test_requirements make new installs fail

### ISSUE THREAD

**Issue by mathiser** [Sikerdebaard/dcmrtstruct2nii#38]
... due to cleo. 
The library is not compatible with cleo ver. 2.0.1, and should probably be kept at 0.8.1

Mathis

**Comment by Sikerdebaard** [comment]
Thanks, I'll probably update to the new version of cleo if it isn't too much work. I need to work on the unit tests anyways as they are currently failing due to slightly different IoU scores between versions.

**Comment by Sikerdebaard** [comment]
This is now resolved in the new version. Cleo has been updated to >=2.x.x. Closing.
