### ISSUE TITLE
Segmentation masks for multiple organs are placed in the same NII .gz file

### ISSUE THREAD

**Issue by LReion** [Sikerdebaard/dcmrtstruct2nii#45]
I have an RT file and a DICOM folder, and I want to put the specified several organs in the same segmentation.nii .gz file, and then add labels to each organ to facilitate the production of the dataset.

**Comment by Sikerdebaard** [comment]
Hi @LReion unfortunately this is currently unsupported by dcmrtstruct2nii. The reason for this is that structures can overlap and there is currently no strategy implemented to resolve overlaps.

Perhaps fslutils has a tool to do what you want. For example you could merge the NIfTI file outputs from dcmrtstruct2nii with fslmerge or perhaps fslroi.

https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/Fslutils
