### ISSUE TITLE
InvalidFileFormatException

### ISSUE THREAD

**Issue by fishdda** [Sikerdebaard/dcmrtstruct2nii#7]
InvalidFileFormatException: File C:/GitFolder/RL-Application-in-TPS/AUTO-PLANNING/AutoTemplateTuning/projects/dose prediction/DATA/003/003_StrctrSets.dcm is not an rt-struct dicom

Do you know why this error occurs?

**Comment by Sikerdebaard** [comment]
Mostlikely this is caused because the program can't find the 'StructureSetROISequence' in the RT-Struct file.

The error most likely originates from this line of code: https://github.com/Sikerdebaard/dcmrtstruct2nii/blob/master/dcmrtstruct2nii/adapters/input/contours/rtstructinputadapter.py#L19
